language: go
services:
  - mysql

env:
  - SUITE=lint
  - SUITE=test

go:
  - 1.11.x
  - 1.10.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - make dep
  - mysql -e 'CREATE DATABASE certs;'

install:
  - go version

sudo: false
script:
  - MYSQL_TEST="true" make $SUITE

after_success:
  - bash <(curl -s https://codecov.io/bash)
